### ISSUE TITLE
Add initial code

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-integration-lineage-event-driven-sample#4]
- [x] add initial code 
- [x] correct packages 
- [x] correct connector name
- [x] create assets junits
- [x] create process junits
- [x] create schematype junits
- [x] create schemaAttributes junits
- [x] update asset junitsjunit
- [x] update process junits
- [x] update schematype junits
- [x] update schemaAttributes junits
- [x] delete schematype junits
- [x] delete schemaAttributes
- [x] check audit log and error log content
- [x] readme / docs
- [x] test create EventType, assets and attributes  are catalogued and confirm lineage is as expected
- [x] test update EventType,  assets and attributes are correctly cataloged and confirm lineage is as expected
- [x]  test update of the datatype -currently not working - see  issue [https://github.com/odpi/egeria/issues/7147](https://github.com/odpi/egeria/issues/7147), this is changing the attribute type integer to string.  
- [x] test delete EventType  and attributes are not cataloged after the delete
- [x] test create update of formula in schema attributes
- [x] test update dataflow to change SQL
- [x] create postman collection
- [x] agree approach to handle existing content. Amend the logic in the connector as follows - on stakeholder request. This may not be possible -see [https://github.com/odpi/egeria/issues/7226](https://github.com/odpi/egeria/issues/7226).
```
 if the topic exists then use it
else reject the metadata
if the EventType exists then use it
else create it and assume that you will stay the owner forever
```
- [ ] Test with existing topic content

**Comment by planetf1** [comment]
There's a few 'TODO:' items in the project which relate to updating artifact names etc - they may be helpful

**Comment by davidradl** [comment]
Raised issue [https://github.com/odpi/egeria/issues/7122](https://github.com/odpi/egeria/issues/7122) to be able to get existing Dataflow relationships associated with a process. We need this to work out which dataflows and assets need to be deleted.

**Comment by davidradl** [comment]
Raised issue [https://github.com/odpi/egeria/issues/7134 ](https://github.com/odpi/egeria/issues/7134) to allow EventTypeLists to be added to Egeria lineage context. This would allow this connector to catalog multiple EventTypes under an asset

**Comment by davidradl** [comment]
All addressed - still waiting for datatype update issue #7147 to be merged,
