### ISSUE TITLE
Kafka Consumer Properties are ignored

### ISSUE THREAD

**Issue by juergenhemelt** [odpi/egeria-connector-integration-lineage-event-driven-sample#42]
The consumer properties of the connector are ignored. When changing the `bootstrap.servers` configuration of the consumer the connector still tries to connect to `localhot:9092`(the default value).

**Comment by juergenhemelt** [comment]
I found 2 causes here:
1. The connector uses a `OpenMetadataTopicConnector`and not a `KafkaOpenMetadataTopicConnector`
2. The properties of the producer are not set but the embedded connector always tries to connect to both the producer and the consumer and as the producer is checked first it fails.

**Comment by juergenhemelt** [comment]
First reason is not valid as it executes the correct inherited methods when we configure a `KafkaOpenMetadataTopicConnector`. The second reason is an issue in Egeria itself. So I will close this one and create one in the Egeria repository.

**Comment by planetf1** [comment]
As a FYI it's possible for an issue to be transferred from one repo to another (it may only be a maintainer that can do this - ot sure).
