### ISSUE TITLE
It should possible to get all schema types of an asset

### ISSUE THREAD

**Issue by dbruns91** [odpi/egeria-connector-integration-lineage-event-driven-sample#61]
When I try the following POST-Call:

`{{mds-baseURL}}/servers/{{mds-server}}/open-metadata/access-services/asset-manager/users/{{user}}/parents/{{parent-asset-type-name}}/{{parent-asset-type-guid}}/schema-types/retrieve?forLineage=true&forDuplicateProcessing=true`

with RequestBody:

`{
    "effectiveTime": null,
    "assetManagerGUID" : "{{assetManagerGUID}}",
    "assetManagerName": "{{assetManagerName}}"
}`

I expected to get a list of all schema types connected with the assest. Instead I get the following error:

`{
    "class": "SchemaTypeElementResponse",
    "relatedHTTPCode": 404,
    "exceptionClassName": "org.odpi.openmetadata.frameworks.connectors.ffdc.PropertyServerException",
    "actionDescription": "getSchemaTypeForElement",
    "exceptionErrorMessage": "OMAG-REPOSITORY-HANDLER-404-006 Multiple AssetSchemaType relationships are connected to the Asset entity with unique identifier 74cb3f35-0814-4d4b-85ef-c8aeb058dc8f: the relationship identifiers are [7eaf89cc-50d9-440d-9f3a-7fd8ac02a412, a1df269d-903a-40fd-b102-5b49302a462c, e038b495-1805-49d6-886f-987f6f2da8b9]; the calling method is getSchemaTypeForElement and the server is mds1",
    "exceptionErrorMessageId": "OMAG-REPOSITORY-HANDLER-404-006",
    "exceptionErrorMessageParameters": [
        "AssetSchemaType",
        "Asset",
        "74cb3f35-0814-4d4b-85ef-c8aeb058dc8f",
        "[7eaf89cc-50d9-440d-9f3a-7fd8ac02a412, a1df269d-903a-40fd-b102-5b49302a462c, e038b495-1805-49d6-886f-987f6f2da8b9]",
        "getSchemaTypeForElement",
        "mds1"
    ],
    "exceptionSystemAction": "The system is unable to process a request because multiple relationships have been discovered and it is unsure which relationship to follow.",
    "exceptionUserAction": "Investigate why multiple relationships exist.  Then retry the request once the issue is resolved."
}`

**Comment by davidradl** [comment]
As per conversation today the error is occurring with code in an private branch. We talked of surfacing this code in a pr that can be reviewed and merged by the community.

**Comment by dbruns91** [comment]
Hey @davidradl 
the pr is created: https://github.com/odpi/egeria-connector-integration-lineage-event-driven-sample/pull/63

**Comment by dbruns91** [comment]
I will close this and deliver more information (with a working pr).

**Comment by davidradl** [comment]
Hi @dbruns91 we should leave the issue open until the pr is closed.

**Comment by dbruns91** [comment]
Hi @davidradl  thats fine. I forgot about that. This is the correct pr:
https://github.com/odpi/egeria-connector-integration-lineage-event-driven-sample/pull/66

**Comment by dbruns91** [comment]
I will close this due the changes which done here
https://github.com/odpi/egeria/issues/7692
