### ISSUE TITLE
the Lineage context has a null userId at the latest Egeria code. 

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-connector-integration-lineage-event-driven-sample#67]
The Lineage sample used to work at Egeria v3.15. It now fails using version 4 because the LineageIntegrationContext has a null userId in it. when we issue the call `myContext.getDataAssetsByName ` the server rejects this call due the the null userId.
the configuration of the sample lineage server has     `"localServerUserId": "OMAGServer",` I am not sure why it is not picking this up

**Comment by dbruns91** [comment]
@davidradl  For testing purposes I need an egeria base v4 server, am I right?

**Comment by davidradl** [comment]
@dbruns91 I just checked the connector is building against Egeria 3.15. That is what I tested with when I created the connector.

I was trying to testing using a v4 egeria runtime - which I think is incorrect and probably why I got this error.

I will close this issue as it was an invalid test
